name: Build Workflow

on:
  push:
#    branches: master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: download and install PySVN
        run: |
          curl.exe -o .\pysvn_installer.exe "https://sourceforge.net/projects/pysvn/files/pysvn/V1.9.23/Windows/py313-pysvn-svn1144-1.9.23-2129-Win64.exe/download"
          .\pysvn_installer.exe
      - name: Run PyInstaller
        run: |
          python -m PyInstaller svn_rev_update.spec
      - uses: actions/upload-artifact@v4
        with:
          name: SVN_rev_update_EXE
          path: dist/svn_rev_update.exe
